BOARD_SIZE = 8
SQUARE_SIZE = 100
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 800

WHITE = "white"
BLACK = "black"

PAWN = "PAWN"
ROOK = "ROOK"
KNIGHT = "KNIGHT"
BISHOP = "BISHOP"
QUEEN = "QUEEN"
KING = "KING"

WHITE_BISHOP_IMAGE = "Assets/BishopW.png"
WHITE_KING_IMAGE = "Assets/KingW.png"
WHITE_KNIGHT_IMAGE = "Assets/KnightW.png"
WHITE_PAWN_IMAGE = "Assets/PawnW.png"
WHITE_QUEEN_IMAGE = "Assets/QueenW.png"
WHITE_ROOK_IMAGE = "Assets/RookW.png"

BLACK_BISHOP_IMAGE = "Assets/BishopB.png"
BLACK_KING_IMAGE = "Assets/KingB.png"
BLACK_KNIGHT_IMAGE = "Assets/KnightB.png"
BLACK_PAWN_IMAGE = "Assets/PawnB.png"
BLACK_QUEEN_IMAGE = "Assets/QueenB.png"
BLACK_ROOK_IMAGE = "Assets/RookB.png"

pieces = [ROOK, KNIGHT, BISHOP, QUEEN, KING, BISHOP, KNIGHT, ROOK]
whitePieceImages = [WHITE_ROOK_IMAGE, WHITE_KNIGHT_IMAGE, WHITE_BISHOP_IMAGE, WHITE_QUEEN_IMAGE, WHITE_KING_IMAGE, WHITE_BISHOP_IMAGE, WHITE_KNIGHT_IMAGE, WHITE_ROOK_IMAGE]
blackPieceImages = [BLACK_ROOK_IMAGE, BLACK_KNIGHT_IMAGE, BLACK_BISHOP_IMAGE, BLACK_QUEEN_IMAGE, BLACK_KING_IMAGE, BLACK_BISHOP_IMAGE, BLACK_KNIGHT_IMAGE, BLACK_ROOK_IMAGE]
